# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 10:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_auto_20170804_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railcars',
            name='fuel_brand',
        ),
        migrations.AddField(
            model_name='bills',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата платежа'),
        ),
        migrations.AddField(
            model_name='bills',
            name='supplier',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='bills',
            name='supply_date',
            field=models.DateField(null=True, verbose_name='Дата поставки'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Введите количество топлива в килограммах.', max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='railcar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Railcars', verbose_name='Вагон'),
        ),
    ]
