# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170829_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill',
            field=models.CharField(max_length=32, unique=True, verbose_name='Платёж'),
        ),
    ]
