# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170829_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterModelOptions(
            name='fueltypes',
            options={'verbose_name': 'тип топлива', 'verbose_name_plural': 'типы топлива'},
        ),
        migrations.AlterModelOptions(
            name='railcars',
            options={'verbose_name': 'вагон', 'verbose_name_plural': 'вагоны'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'принятый вагон', 'verbose_name_plural': 'принятые вагоны'},
        ),
        migrations.AlterField(
            model_name='bills',
            name='bill',
            field=models.CharField(max_length=32, unique=True, verbose_name='Номер платежа'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='supplier',
            field=models.CharField(max_length=32, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='supply_date',
            field=models.DateField(default=tracker.models.month_limit, help_text='Укажите предполагаемую дату поставки', verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='fueltypes',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ИД'),
        ),
        migrations.AlterField(
            model_name='fueltypes',
            name='type',
            field=models.CharField(max_length=4, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='railcars',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.Bills', verbose_name='платеж'),
        ),
        migrations.AlterField(
            model_name='railcars',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.FuelTypes', verbose_name='тип топлива'),
        ),
        migrations.AlterField(
            model_name='railcars',
            name='railcar',
            field=models.CharField(max_length=8, verbose_name='вагон'),
        ),
        migrations.AlterField(
            model_name='railcars',
            name='volume',
            field=models.DecimalField(decimal_places=4, help_text='Введите количество топлива в килограммах', max_digits=10, verbose_name='объем'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='сотрудник'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Введите количество топлива в килограммах', max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время'),
        ),
    ]
