# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170907_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='railcars',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='принят'),
        ),
    ]
