# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_railcars_is_accepted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'permissions': (('view_bills', 'Пользователь может просматривать счета'),), 'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'permissions': (('view_tracking', 'Пользователь может просматривать принятые вагоны'),), 'verbose_name': 'принятый вагон', 'verbose_name_plural': 'принятые вагоны'},
        ),
    ]
