# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_tracking_release_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bills',
            options={'permissions': (('view_bills', 'Пользователь может просматривать сделки'),), 'verbose_name': 'сделка', 'verbose_name_plural': 'сделки'},
        ),
        migrations.RemoveField(
            model_name='bills',
            name='supply_date',
        ),
        migrations.AddField(
            model_name='bills',
            name='payment_date',
            field=models.DateField(help_text='Оставьте поле пустым, если слелка ещё не оплачена', null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='release_time',
            field=models.DateTimeField(null=True, verbose_name='отпущен в      '),
        ),
    ]
