# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20171023_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='release_time',
            field=models.DateTimeField(null=True, verbose_name='отпущен в '),
        ),
    ]
