# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20171024_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='volume',
            field=models.IntegerField(default=60, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='bills',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Оставьте поле пустым, если слелка ещё не оплачена', null=True, verbose_name='Дата оплаты'),
        ),
    ]
